version: '3.8'

services:
  nextjs:
    build: .
    ports:
      - "3000:3000"  # External:Internal
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://127.0.0.1:8000
      - NEXT_PUBLIC_BASE_URL=https://otakustream.xyz
    networks:
      - nextjs-network
    restart: unless-stopped

networks:
  nextjs-network:
    driver: bridge