version: '3.8'

services:
  nextjs:
    build: .
    ports:
      - "80:3000"  # External:Internal
    environment:
      - NODE_ENV=production
    networks:
      - nextjs-network
    restart: unless-stopped

networks:
  nextjs-network:
    driver: bridge